# Etapa 1: Build do React app
FROM node:20 as builder
WORKDIR /app

COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build

# Etapa 2: Nginx para servir o app
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiar y preparar el script de entrypoint
COPY env.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
